releases/20160720091944/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions , only: [:new, :create, :destroy]
  resources :microposts , only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to:'static_pages#help',     via: 'get'
  match '/about',   to:'static_pages#about',    via: 'get'
  match '/contact', to:'static_pages#contact',  via: 'get'  
  match '/signup',  to:'users#new',             via: 'get'
  match '/signin',  to:'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

releases/20160720091944/app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	validates :user_id , presence: true
	validates :content , presence: true, length: {maximum: 140 }
	default_scope -> { order('created_at DESC')}
	
end

releases/20160720091944/app/models/user.rb
class User < ActiveRecord::Base
    has_many :microposts, dependent: :destroy
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:name , presence: true , length: { maximum: 50} )
	validates :email, presence: true, 
					format: { with: VALID_EMAIL_REGEX },
                	uniqueness: {case_sensitive: false}
    validates :password , length:{minimum: 6}
    before_save {self.email = email.downcase}
    before_create :create_remember_token
    has_secure_password

    def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
    end

    def User.new_remember_token
    	SecureRandom.urlsafe_base64
    end
    def User.digest(token)
    	Digest::SHA1.hexdigest(token.to_s)
    end

    private
    	def create_remember_token
    		self.remember_token = User.digest(User.new_remember_token)
    	end
end

releases/20160720091944/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

releases/20160720091944/app/controllers/concerns/microposts_controller_tmp.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy 

   def index
  end
  def create
  	@micropost = current_user.microposts.build(microposts_params)
  	if @micropost.save
  		flash[:success] ="Micropost created!"
  		redirect_to root_url
  	else 
  		@feed_iemts =[]
  		render 'static_pages/home'
  	end
  end

  def destroy
  	@micropost.destroy
  	redirect_to root_url
  end

  private 
  def microposts_params
  params.require(:micropost).permit(:content)
  end
  def correct_user
  	@micropost = current_user.microposts.find_by(id: params[:id])
  	redirect_to root_url if @micropost.nil?
  end
end

releases/20160720091944/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy 

   def index
  end
  def create
  	@micropost = current_user.microposts.build(microposts_params)
  	if @micropost.save
  		flash[:success] ="Micropost created!"
  		redirect_to root_url
  	else 
  		@feed_iemts =[]
  		render 'static_pages/home'
  	end
  end

  def destroy
  	@micropost.destroy
  	redirect_to root_url
  end

  private 
  def microposts_params
  params.require(:micropost).permit(:content)
  end
  def correct_user
  	@micropost = current_user.microposts.find_by(id: params[:id])
  	redirect_to root_url if @micropost.nil?
  end
end

releases/20160720091944/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user= User.find_by(email: params[:session][:email].downcase)

		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
    sign_out
    redirect_to root_url
  end

end

releases/20160720091944/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  	@micropost = current_user.microposts.build 
  	@feed_items = current_user.feed.paginate(page: params[:page])
  end
  end

  def help
  end

  def about
  end

  def contact
  end
end

releases/20160720091944/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def index
    @users =User.paginate(page: params[:page])
  end
  def new
  	@user=User.new
  end
  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

  end
  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App"
  		redirect_to @user
  	else
  		render 'new'
  	end	
  end
  def edit
    #@user = User.find(params[:id])
  end
  def update
    #@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private 
    def sign_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in." 
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

  	def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    def admin_user
        unless current_user.admin
         redirect_to root_url
         end 
    end
end

releases/20160720091944/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
     base_title= "Ruby on Rails Tutorial Sample App"
     if page_title.empty? 
	base_title
     else 
        "#{base_title} | #{page_title}"
     end
  end
end

releases/20160720091944/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end
	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in_user
	    unless signed_in?
	      store_location
	      redirect_to signin_url, notice: "Please sign in."
	    end
  	end

	def signed_in?
 nil
	end
	def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
  	user == current_user
  end

  def redirect_back_or(default)
  	redirect_to(session[:return_to] || default)
  	session.delete(:return_to)
  end

  def store_location
  	session[:return_to] = request.url if request.get?
  end
  
end

releases/20160720091944/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

releases/20160720091944/app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for (user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name , class: "gravatar")
	end
end

releases/20160720091944/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer> 

releases/20160720091944/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Accont <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Setting", edit_user_path(current_user) %></li>
                <li class="divider" ></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

releases/20160720091944/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

releases/20160720091944/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value|%>
		<div class="alert alert- <%= key %>"> <%= value %> </div>
		<% end %>
		<%= yield %>
		<%= render  'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

releases/20160720091944/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
    <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
    	<li> * <%= msg%> </li>
    <%end%>
    </ul>
    </div>
<%end%>

releases/20160720091944/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

releases/20160720091944/app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

releases/20160720091944/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

releases/20160720091944/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>