config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions , only: [:new, :create, :destroy]
  resources :microposts , only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to:'static_pages#help',     via: 'get'
  match '/about',   to:'static_pages#about',    via: 'get'
  match '/contact', to:'static_pages#contact',  via: 'get'  
  match '/signup',  to:'users#new',             via: 'get'
  match '/signin',  to:'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  namespace :api do
    resources :microposts
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li> * <%= msg%> </li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <br />

  title
  <span class="title">
  <%= link_to sanitize(feed_item.title), feed_item %>
  </span>
  <br />

  content
  <span class="content">
  <%= link_to sanitize(feed_item.content), feed_item %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.haml
= link_to "New Post", new_micropost_path, class: "btn btn-large btn-primary"

app/views/shared/_stats.html.erb
<% @user ||=current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
	<strong id="following" class="stat">
		<%= @user.followed_users.count %>
	</strong>
	following
	</a>
	<a href="<%= followers_user_path(@user)%>">
	<strong id="followers" class="stat">
	<%= @user.followers.count%>
	</strong>
	followers
	</a>
</div>